FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /wallet-server ./cmd/wallet_server
FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=build /wallet-server /app/wallet-server
ENV PORT=5000
EXPOSE 5000
CMD ["/app/wallet-server"]
